### ISSUE TITLE
Scroll bar in text box disappears after window size change, but is needed

### ISSUE THREAD

**Issue by haimat** [cnjinhao/nana#193]
I noticed a bug with scroll bars in text boxes, hopefully I can describe it well enough.

When you have a `form` (as window) in a certain size but not full screen, and as child widget a `textbox`, after appending enough lines to the text box, a scroll bar appears. This obviously is correct behaviour. Then scroll down so that the first lines in the text box are not visible, the scroll bar is at the "lowest" position.

Now when you make the window full screen, so that all text would fit into the text box, the scroll bar disappears correctly. However, the first lines that have been invisible before (when then window was small) are still not visible. But since the scroll bar is gone, you cannot scroll up again to see those top lines.

Any ideas?

**Comment by cnjinhao** [comment]
Thank you for reporting this issue. Get it, I will check it later.

**Comment by cnjinhao** [comment]
Hi, @haimat The bug is fixed, please use the latest hotfix branch.

**Comment by haimat** [comment]
Hi @cnjinhao, I updated the file `text_editor.cpp` and recompiled.
Unfortunately though this did not fix the problem :(

**Comment by cnjinhao** [comment]
Hi, did you try the fix 54cb64b991b1b5033586a991e0b52be27b04aef2?

**Comment by haimat** [comment]
Yes, as said, I used the last version of the file `text_editor.cpp`, replaced my local version of it, recompiled, and tried again. But without luck :(

**Comment by cnjinhao** [comment]
I can't reproduce the issue. Please try the following program to see whether it can reproduce the issue.

``````c++
#include <nana/gui.hpp>
#include <nana/gui/widgets/textbox.hpp>

int main()
{
	using namespace nana;

	form fm;
	textbox text{ fm };

	fm.div("margin=15 txt");
	fm["txt"] << text;
	fm.collocate();

	std::string str;
	for (auto i = 0; i < 26; ++i)
	{
		for (auto u = 'a'; u <= 'a' + i; ++u)
			str += u;
		str += '\n';
	}

	text.caption(str);

	fm.show();
	exec();
}
``````
Thanks in advance.

**Comment by haimat** [comment]
Works, thanks!
